-- New tables for Google Calendar-driven time tracker
CREATE TABLE IF NOT EXISTS "calendar_watch" (
	"user_id" text DEFAULT 'default' NOT NULL,
	"calendar_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"resource_id" text NOT NULL,
	"expiration" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "calendar_watch_user_id_pk" PRIMARY KEY("user_id")
);

CREATE TABLE IF NOT EXISTS "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" text NOT NULL UNIQUE,
	"archived" integer DEFAULT 0 NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Replace work_segments with new structure (unique calendar_id + external_id + date)
DROP TABLE IF EXISTS "work_segments";
CREATE TABLE "work_segments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"calendar_id" text NOT NULL,
	"external_id" text NOT NULL,
	"date" text NOT NULL,
	"title" text,
	"category" text NOT NULL,
	"duration_minutes" integer NOT NULL,
	"start_at" timestamp with time zone,
	"end_at" timestamp with time zone,
	"synced_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "work_segments_calendar_id_external_id_date_unique" UNIQUE("calendar_id","external_id","date")
);

-- daily_totals and app_config (required by app)
CREATE TABLE IF NOT EXISTS "daily_totals" (
	"date" text PRIMARY KEY NOT NULL,
	"total_minutes" integer DEFAULT 0 NOT NULL,
	"minutes_by_category" jsonb DEFAULT '{}' NOT NULL,
	"overtime_balance_after" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "app_config" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Ensure google_tokens exists (may already exist from prior setup)
CREATE TABLE IF NOT EXISTS "google_tokens" (
	"user_id" text DEFAULT 'default' NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text,
	"expires_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "google_tokens_user_id_pk" PRIMARY KEY("user_id")
);

-- Drop old tables no longer used
DROP TABLE IF EXISTS "ticktick_tokens";
DROP TABLE IF EXISTS "microsoft_tokens";
DROP TABLE IF EXISTS "category_mapping";
DROP TABLE IF EXISTS "sync_state";

-- Seed default categories (ignore if already exist)
INSERT INTO categories (name, archived, display_order) VALUES
  ('Learning', 0, 0),
  ('1:1s', 0, 1),
  ('General tasks/meetings', 0, 2)
ON CONFLICT (name) DO NOTHING;
