-- Events table: source of truth for time entries (date, name, category, length_hours)
CREATE TABLE IF NOT EXISTS "events" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "date" text NOT NULL,
  "name" text NOT NULL,
  "category" text NOT NULL,
  "length_hours" real NOT NULL,
  "source_type" text NOT NULL DEFAULT 'manual',
  "source_id" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "events_date_source_type_source_id_unique" UNIQUE("date","source_type","source_id")
);

-- Backfill from work_segments into events only if that table exists
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'work_segments') THEN
    INSERT INTO events (date, name, category, length_hours, source_type, source_id, created_at, updated_at)
    SELECT
      ws.date,
      COALESCE(ws.title, 'Event'),
      ws.category,
      ws.duration_minutes / 60.0,
      'google',
      ws.calendar_id || ':' || ws.external_id,
      COALESCE(ws.synced_at, now()),
      now()
    FROM work_segments ws
    ON CONFLICT (date, source_type, source_id) DO NOTHING;
  END IF;
END $$;

-- Seed: 2025 summary (single entry for pre-2026)
INSERT INTO events (date, name, category, length_hours, source_type, source_id)
VALUES ('2025-12-31', 'Summary of time from 2025', 'General tasks/meetings', 27.5, 'manual', '2025-summary')
ON CONFLICT (date, source_type, source_id) DO NOTHING;

-- Backfill from daily_totals.minutes_by_category into events (one event per category per day)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'daily_totals' AND column_name = 'minutes_by_category'
  ) THEN
    INSERT INTO events (date, name, category, length_hours, source_type, source_id, created_at, updated_at)
    SELECT
      d.date,
      cat.key,
      cat.key,
      (cat.value::numeric / 60.0),
      'manual',
      'dt-' || d.date || '-' || regexp_replace(regexp_replace(cat.key, '\s+', '-', 'g'), '/', '-'),
      now(),
      now()
    FROM daily_totals d,
    LATERAL jsonb_each_text(COALESCE(d.minutes_by_category, '{}'::jsonb)) AS cat(key, value)
    WHERE d.minutes_by_category IS NOT NULL
      AND jsonb_typeof(d.minutes_by_category) = 'object'
      AND cat.value ~ '^\d+\.?\d*$'
    ON CONFLICT (date, source_type, source_id) DO NOTHING;
  END IF;
END $$;

-- Seed: Jan 14 2026 (from spreadsheet)
INSERT INTO events (date, name, category, length_hours, source_type, source_id) VALUES
  ('2026-01-14', 'WSBC General Meetings', 'General tasks/meetings', 2.75, 'manual', 'jan14-meetings'),
  ('2026-01-14', 'WSBC General Tasks', 'General tasks/meetings', 4.5, 'manual', 'jan14-tasks'),
  ('2026-01-14', 'PIS Enhance', 'PIS Enhance', 1.5, 'manual', 'jan14-pis'),
  ('2026-01-14', 'DocUploader & PXT', 'DocUploader', 0.5, 'manual', 'jan14-docuploader')
ON CONFLICT (date, source_type, source_id) DO NOTHING;

-- Slim daily_totals: drop derived columns (totals now come from events)
ALTER TABLE "daily_totals" DROP COLUMN IF EXISTS "total_minutes";
ALTER TABLE "daily_totals" DROP COLUMN IF EXISTS "minutes_by_category";

-- Remove work_segments (replaced by events)
DROP TABLE IF EXISTS "work_segments";
